version: '3.8'

services:
  dbt_dpd:
    image: ghcr.io/dbt-labs/dbt-bigquery:latest
    container_name: dbt_dpd
    restart: always
    volumes:
      - ./dbt_dpd:/usr/app/dbt  
      - ./credentials.json:/usr/app/dbt/credentials.json  
      - ./dbt_dpd/profiles.yml:/root/.dbt/profiles.yml  
    working_dir: /usr/app/dbt  
    entrypoint: ["/bin/bash", "-c", "sleep infinity"]  
