services:
  postgres_docker:
    image: "postgres:13"
    ports:
      - "5434:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=prod_airflow
      - POSTGRES_PASSWORD=prod_airflow
      - POSTGRES_DB=prod_purwadika
