version: 2

sources:
  - name: diego_library
    schema : diego_library_finpro
    tables:
      - name: users_data
        identifier: users
      - name: books_data
        identifier: books
      - name: rents_data
        identifier: rents

  