name: 'dbt_dpd'
version: '1.0.0'
config-version: 2

profile: 'dbt_dpd'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_dpd:
    staging:
      +materialized: view
      +schema: diego_dwh_library_staging
      +persists_docs:
        relation: true
        columns: true
      tag: staging

    dimfact:
      +materialized: view
      +schema: diego_dwh_library_dimfact
      +persists_docs:
        relation: true
        columns: true
      tag: dimfact
      
    datamart:
      +materialized: view
      +schema: diego_dwh_library_marts
      +persists_docs:
        relation: true
        columns: true
      tag: mart
