version: '3.8'

services:
  project_capstone:
    image: postgres:latest
    environment:
      POSTGRES_USER: dewa_final
      POSTGRES_PASSWORD: dewa_final
      POSTGRES_DB: final_project
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: